/*
 * This source file was generated by the Gradle 'init' task
 */
package csc_projects;

public class Module2 {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Module2().getGreeting());
    }
}
