/*
 * This source file was generated by the Gradle 'init' task
 */
package csc_projects;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Module3 classUnderTest = new Module3();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
